### ISSUE TITLE
Uncaught (in promise) SyntaxError: ambiguous indirect export: encode

### ISSUE THREAD

**Issue by socketopp** [Rich-Harris/magic-string#270] opened 2024-01-24 09:51 UTC
I have a few projects that are dependent on magic-string.  I saw in the console log that it have an uncaught error and thought I'd should alert the team behind the lib about it.
![bild](https://github.com/kbrgl/svelte-french-toast/assets/20456621/f6d18913-2847-4552-939b-5784ba83de4c)

Here are some of my dependencies that rely on this library. 
```
$ npm list magic-string
├─┬ @sentry/svelte@7.95.0
│ └── magic-string@0.30.5
├─┬ @sentry/vite-plugin@2.10.3
│ └─┬ @sentry/bundler-plugin-core@2.10.3
│   └── magic-string@0.27.0
├─┬ @sveltejs/kit@2.4.3
│ └── magic-string@0.30.5 deduped
├─┬ @sveltejs/vite-plugin-svelte@3.0.1
│ └── magic-string@0.30.5 deduped
├─┬ svelte-check@3.6.3
│ └─┬ svelte-preprocess@5.1.3
│   └── magic-string@0.30.5 deduped
├─┬ svelte@5.0.0-next.37 invalid: "^3.54.0 || ^4.0.0 || ^5" from node_modules/@auth/sveltekit, "3.x || 4.x" from node_modules/@sentry/svelte, "^3.57.0 || ^4.0.0" from node_modules/svelte-french-toast
│ └── magic-string@0.30.5 deduped
└─┬ wrangler@3.24.0
  └─┬ @esbuild-plugins/node-modules-polyfill@0.2.2
    └─┬ rollup-plugin-node-polyfills@0.2.1
      └─┬ rollup-plugin-inject@3.0.2
        └── magic-string@0.25.9
```

The error points to this line of code:
`node_modules/magic-string/dist/magic-string.es.mjs?v=0a750443`
```
import { encode } from "/node_modules/@jridgewell/sourcemap-codec/dist/sourcemap-codec.umd.js?v=0a750443";
```

**Comment by antfu** [comment] 2024-04-10 03:13
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-10 03:13 UTC
