### ISSUE TITLE
SourceMap class didn't export at magic-string.cjs.js

### ISSUE THREAD

**Issue by bluelovers** [Rich-Harris/magic-string#170] opened 2019-12-27 20:04 UTC
`SourceMap` class didn't export at magic-string.cjs.js

**Comment by antfu** [comment] 2022-03-02 18:46
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-03-02 18:46 UTC
Labels: bug
